# 应用服务 WEB 访问端口
server:
  port: 8080
spring:
  thymeleaf:
    cache: false
logging:
  file:
    path: logs/
    name: logs/sallai.log
  level:
    root: info

logview:
  enable: true
  loginName: sallai
  loginPassword: 123456